mlog_project/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import (SignUpView, 
					LoginView, 
					UserDetailView, 
					UserUpdateView, 
					UserEntryListView,
					UserPasswordChangeView,
					UserPasswordChangeDoneView,
					UserPasswordResetView,
					UserPasswordResetDoneView,
					UserPasswordResetConfirmView,
					UserPasswordResetCompleteView,
					UserActiveStatusUpdateView,
)

app_name = 'accounts'
urlpatterns = [
	path('signup/',SignUpView.as_view(), name='signup'),
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', LogoutView.as_view(template_name='accounts/loggedout.html'), name='logout'),

	path('password/', UserPasswordChangeView.as_view(), name='password'),
	path('password/changed/', UserPasswordChangeDoneView.as_view(), name='passwordchanged'),
	path('password/reset/', UserPasswordResetView.as_view(), name='passwordreset'),
	path('password/reset/done/', UserPasswordResetDoneView.as_view(), name='passwordresetdone'),
	path('password/reset/confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='passwordresetconfirm'),
	path('password/reset/complete/', UserPasswordResetCompleteView.as_view(), name='passwordresetcomplete'),
	
	path('detail/<str:username>/', UserDetailView.as_view(), name='detail'),
	path('detail/<str:username>/entry/', UserEntryListView.as_view(), name='userentrylist'),
	path('update/', UserUpdateView.as_view(), name='update'),
	path('update/active_status/', UserActiveStatusUpdateView.as_view(), name='active_status'),
]

mlog_project/comments/urls.py
from django.urls import path

from .views import (
	CommentCreateView,
	CommentListView,
	CommentUpdateView,
	CommentDeleteView,
)

app_name='comments'
urlpatterns=[
	path('create/<int:pk>/', CommentCreateView.as_view(), name='create'),
	path('list/<int:pk>/', CommentListView.as_view(), name='list'),
	path('update/<int:pk>/', CommentUpdateView.as_view(), name='update'),
	path('delete/<int:pk>/', CommentDeleteView.as_view(), name='delete'),
]

mlog_project/entry/urls.py
from django.urls import path, include

from .views import (
	EntryDetailView,
	EntryCreateView,
	EntryUpdateView,
	EntryDeleteView,
	EntryListBySongView,
	EntryListByArtistView
)

app_name='entry'

urlpatterns=[
	path('create/', EntryCreateView.as_view(), name='create'),
	path('detail/<int:pk>/', EntryDetailView.as_view(), name='detail'),
	path('update/<int:pk>/', EntryUpdateView.as_view(), name='update'),
	path('delete/<int:pk>/', EntryDeleteView.as_view(), name='delete'),

	path('list/song/<int:pk>/', EntryListBySongView.as_view(), name='entry_list_by_song'),
	path('list/artist/<slug:slug>/', EntryListByArtistView.as_view(), name='entry_list_by_artist'),

	path('select2/', include('django_select2.urls')),
]

mlog_project/likes/urls.py
from django.urls import path

from .views import EntryLikedUserListView, UserLikedEntryListView, like_process

app_name='likes'
urlpatterns=[
	path('like/', like_process, name='like'),
	path('user_liked_entry_list/<str:username>/', UserLikedEntryListView.as_view(), name='user_liked_entry_list'),
	path('entry_liked_user_list/<int:pk>/', EntryLikedUserListView.as_view(), name='entry_liked_user_list'),
]

mlog_project/mlog/urls.py
from django.urls import path

from .views import (
					RootRedirectView,
					TopView, 
					TimelineView, 
					login_as_sample_user,
				)

app_name='mlog'
urlpatterns=[
	path('', RootRedirectView.as_view(), name='rootredirect'),
	path('top/', TopView.as_view(), name='top'),
	path('timeline/', TimelineView.as_view(), name='timeline'),
	path('login_as_sample_user/', login_as_sample_user, name='login_as_sample_user'),
]

mlog_project/mlog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import debug_toolbar


urlpatterns = [
    path('mlog_admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='accounts'),
    #path('accounts/', include('allauth.urls')),
    path('', include('mlog.urls'), name='mlog'),
    path('search/', include('search.urls'), name='search'),
    path('comments/', include('comments.urls'), name='comments'),
    path('likes/', include('likes.urls'), name='likes'),
    path('favorites/', include('favorite_artists.urls'), name='favorites'),
    path('follow/', include('follow.urls'), name='follow'),
    path('musics/', include('musics.urls'), name='musics'),
    path('entry/', include('entry.urls'), name='entry'),
    path('notifications/', include('notifications.urls'), name='notifications'),
    path('contacts/', include('contacts.urls'), name='contacts'),
    path('select2/', include('django_select2.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('__debug__/', include(debug_toolbar.urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mlog_project/musics/urls.py
from django.urls import path, include

from .views import (
	ArtistDetailView,
	SongDetailView,
	ArtistCreateView,
	SongCreateView,
	PopupArtistCreateView,
	PopupSongCreateView,
	PopupGenreCreateView,
	GenreCreateView,
	GenreListView,
	ArtistByGenreListView,
	ArtistUpdateView,
	SongUpdateView,
	SongByArtistListView,
	search_spotify_tracks,
	select_spotify_tracks,
)


app_name='musics'

urlpatterns=[
	path('detail/artist/<slug:slug>/', ArtistDetailView.as_view(), name='artist_detail'),
	path('detail/song/<int:pk>/', SongDetailView.as_view(), name='song_detail'),

	path('create/song/', SongCreateView.as_view(), name='song_create'),
	path('create/artist/', ArtistCreateView.as_view(), name='artist_create'),
	path('create/genre/', GenreCreateView.as_view(), name='genre_create'),

	path('create/song/popup/', PopupSongCreateView.as_view(), name='song_create_popup'),
	path('create/artist/popup/', PopupArtistCreateView.as_view(), name='artist_create_popup'),
	path('create/genre/popup/', PopupGenreCreateView.as_view(), name='genre_create_popup'),

	path('update/artist/<str:slug>/', ArtistUpdateView.as_view(), name='artist_update'),
	path('update/song/<int:pk>/', SongUpdateView.as_view(), name='song_update'),

	path('list/genre/', GenreListView.as_view(), name='genre_list'),
	path('list/genre/<str:genre_name>/artist/', ArtistByGenreListView.as_view(), name='artist_by_genre'),
	path('list/artist/<str:slug>/song/', SongByArtistListView.as_view(), name='song_by_artist'),

	path('search_spotify_tracks/', search_spotify_tracks, name='search_spotify_tracks'),
	path('select_spotify_tracks/', select_spotify_tracks, name='select_spotify_tracks'),

	path('select2/', include('django_select2.urls')),
]

mlog_project/entry/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from musics.models import Song
from accounts.models import User


class Entry(models.Model):
	title = models.CharField(verbose_name=_('title'), max_length=30)
	content = models.TextField(_('content'))
	writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='entrys_writer' ,verbose_name=_('writer'))
	created_at = models.DateTimeField(verbose_name=_('created at'))
	updated_at = models.DateTimeField(verbose_name=_('updated at'))
	song = models.ForeignKey(Song, on_delete=models.PROTECT, related_name='featured_song', verbose_name=_('song'))

	def save(self, *args, **kwargs):
		if not self.id:
			self.created_at = timezone.now()
		self.updated_at = timezone.now()
		return super(Entry, self).save(*args, **kwargs)

	def __str__(self):
	    return '%s written by %s (Song:%s)'%(self.title, self.writer,self.song)

mlog_project/entry/forms.py
from django.forms import ModelForm

from django_select2 import forms as s2forms

from .models import Entry


class SongWidget(s2forms.ModelSelect2Widget):
	search_fields = [
		'song_name__icontains',
		'artist__artist_name__icontains'
	]


class EntryForm(ModelForm):
	class Meta:
		model = Entry
		fields = ('title', 'content', 'song')
		widgets = {
			'song':SongWidget,
		}

mlog_project/entry/views.py
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.http import Http404

from activity.models import EntryReadActivity
from accounts.models import User
from likes.models import Like
from comments.models import Comment
from musics.models import Artist, Song

from .models import Entry
from .forms import EntryForm

from activity.tasks import entry_read_activity


class EntryCreateView(LoginRequiredMixin,CreateView):
	form_class = EntryForm
	template_name = 'entry/entry_form.html'

	def form_valid(self, form):
		form.instance.writer = User.objects.get(username=self.request.user.username)
		return super().form_valid(form)

	def get_success_url(self):
		return reverse('entry:detail', kwargs={'pk':self.object.id})


class EntryDetailView(DetailView):
	model = Entry
	template_name = 'entry/detail.html'

	def get(self, request, *args, **kwargs):
		entry_read_activity.delay(self.kwargs.get('pk'), request.user.username)
		return super().get(request, *args, **kwargs)

	def get_object(self):
		obj = super().get_object()
		if obj.writer.is_active:
			return obj
		else:
			raise Http404

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['like_count'] = Like.objects.filter(entry=self.kwargs.get('pk'), user__is_active=True).count()
		context['comment_count'] = Comment.objects.filter(entry=self.kwargs.get('pk'), author__is_active=True).count()
		
		try:
			context['like_status'] = Like.objects.get(user__username=self.request.user.username, entry=self.kwargs.get('pk'))
		except ObjectDoesNotExist:
			context['like_status'] = Like.objects.none()

		context['view_count'] = EntryReadActivity.objects.filter(entry__id=self.kwargs.get('pk')).count()

		return context


class EntryUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	raise_exception = True
	model = Entry
	form_class = EntryForm
	template_name = 'entry/entry_form.html'

	def test_func(self):
		object = self.get_object()
		return object.writer == self.request.user

	def get_success_url(self):
		return reverse('entry:detail', kwargs={'pk':self.object.id})


class EntryDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	raise_exception = True
	model = Entry
	template_name = 'entry/delete_confirm.html'

	def test_func(self):
		object = self.get_object()
		return object.writer == self.request.user

	def get_success_url(self):
		return reverse('accounts:detail', kwargs={'username':self.request.user.username})


class EntryListBySongView(ListView):
	model = Entry
	template_name = 'entry/entry_list.html'
	paginate_by = 12

	def get_queryset(self):
		qs = super().get_queryset()

		try:
			return qs.select_related('writer', 'song').prefetch_related('song__artist').filter(song__id=self.kwargs.get('pk'), writer__is_active=True).order_by('created_at').reverse()
		except ObjectDoesNotExist:
			return qs.none()

	def get_context_data(self, *args, **kwargs) :
		context = super().get_context_data(**kwargs)
		context['song'] = get_object_or_404(Song, id=self.kwargs.get('pk'))
		return context


class EntryListByArtistView(ListView):
	model = Entry
	template_name = 'entry/entry_list.html'
	paginate_by = 12

	def get_queryset(self):
		qs = super().get_queryset()

		try:
			return qs.select_related(
				'writer', 'song'
			).prefetch_related(
				'song__artist'
			).filter(
				song__artist__slug=self.kwargs.get('slug'),
				writer__is_active=True,
			).order_by(
				'created_at'
			).reverse()
		except ObjectDoesNotExist:
			return qs.none()
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['artist'] = get_object_or_404(Artist, slug=self.kwargs.get('slug'))
		return context

mlog_project/templates/entry/create.html
{% extends 'base.html' %}
{% block title%}投稿 | {{block.super}}{% endblock title %}
{% block head %}
	{{ form.media.css }}
	<style>
		input,select{width:50%}
	</style>
{% endblock head %}


{% block content %}
<div class="container">
	<div class "row mt-5">
		<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="投稿">
		</form>
		<a href="javascript:void(0);" onclick="window.open('{% url 'musics:song_create_popup' %}','subwin_song','width=500,height=500');">曲を追加</a>
	</div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{{ form.media.js }}
<script>
	function add_song(name,pk){
		var select=document.getElementById('id_song');
		var option=document.createElement('option');
		option.setAttribute('value',pk);
		option.innerHTML=name;

		select.add(option,0);
		select.options[0].selected=true;
	}
</script>

{% endblock content %}

mlog_project/templates/entry/delete_confirm.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans 'Delete this entry?' %} | {{block.super}}
{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form method="post">
                {% csrf_token %}
                <p>{% trans 'Delete this entry?' %}</p>
				<p>{{entry.content}}</p>
				<p>{{entry.song}}</p>
                <input type="submit" value="{% trans 'Delete' %}">
                <a href="{% url 'entry:detail' entry.id %}"><input type="button" value="{% trans 'Cancel' %}"></a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

mlog_project/templates/entry/detail.html
{% extends 'base.html' %}
{% block title%}{{entry.title}} | {{block.super}}{% endblock title %}
{% block head %}
{% load i18n %}
{% endblock head %}
{% block content %}
<div class="container">
	<div class="row mt-5">
		<div class="row">
			<div class="col">
				<h2>{{entry.title}}</h2>
				<a href="{% url 'accounts:detail' entry.writer %}" style="font-size: large;" class="text-decoration-none">
				<img src="{{MEDIA_URL}}{{entry.writer.profile_image}}" class="profile-image profile-image-size-xs" />
				{{entry.writer.handle}} ({{entry.writer.username}})
				</a>
			</div>
		</div>
		<div class="row my-4">
			<div class="col">
				<button type="submit" id="like-btn"><i class="fa fa-heart {% if like_status %}like-true{% else %}like-false{% endif %}"></i></button>			
			</div>
		</div>
		
		<div class="row my-5">
			{{entry.content|linebreaks}}
			<p>{% trans 'Created at' %}:{{entry.created_at}}</p>
			<p>{% trans 'Updated at' %}:{{entry.updated_at}}</p>
		</div>

		<div class="row mb-3">
			<h3>{% trans 'Featured Song' %}</h3>
			<div class="col">
				<div class="card text-center song-card">
					<div class="card-body">
						<a href="{% url 'musics:song_detail' entry.song.id %}" class="stretched-link text-decoration-none">{{entry.song.song_name}}</a>
					</div>
				</div>
				{% if entry.song.spotify_preview_url %}
				{% include 'common_templates/spotify_preview.html' with artwork_url=entry.song.artwork_url %}
				{% endif %}
				{% if entry.song.spotify_link %}
				{% include 'common_templates/spotify_link.html'  with spotify_link=entry.song.spotify_link %}	
				{% endif %}
			</div>
		</div>

		

		<div class="row mb-3">
			<h3>{% trans 'Artists' %}</h3>
			{% include 'common_templates/artist_card_for_list.html' with artist_list=entry.song.artist.all %}
		</div>

		<div class="row mb-3">
			<div class="col"><a href="{% url 'likes:entry_liked_user_list' entry.id %}" id='liked_user_list_link'>{% trans 'Likes' %}:{{like_count}}</a></div>
			<div class="col"><a href="{% url 'comments:list' entry.id %}">{% trans 'Comments' %}:{{comment_count}}</a></div>
			<div class="col"><p>{% trans 'Views' %}:{{view_count}}</p></div>	
		</div>

		<div class="row mb-3">
			<div class="col"><a href="{% url 'comments:create' entry.id %}"><input type="button" value="{% trans 'Write a comment' %}"></a></div>
		</div>

		<div col="row">
			{% if entry.writer.username == user.username %}
			<a href="{% url 'entry:update' entry.id %}"><input type="button" value="{% trans 'Update' %}"></a><a href="{% url 'entry:delete' entry.id %}"><input type="button" value="{% trans 'Delete' %}"></a>
			{% endif %}
		</div>
	</div>
</div>
{% if entry.song.spotify_preview_url %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/howler/2.2.3/howler.min.js" integrity="sha512-6+YN/9o9BWrk6wSfGxQGpt3EUK6XeHi6yeHV+TYD2GR0Sj/cggRpXr1BrAQf0as6XslxomMUxXp2vIl+fv0QRA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% load static %}
<script src="{% static 'js/howler_handler.js' %}" spotify_preview_url="{{entry.song.spotify_preview_url}}"></script>
{% endif %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% load static %}
<script src="{% static 'js/ajax_csrf.js' %}"></script>
<script src="{% static 'js/like_handler.js' %}" like_url="{% url 'likes:like' %}" entry_id="{{entry.id}}" is_loggedin="{{user.is_authenticated}}"></script>
{% endblock content %}

mlog_project/templates/entry/entry_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block title%}{% trans 'Entry' %} {% if object %}{% trans 'update' %}{% else %}{% trans 'Post' %}{% endif %} | {{block.super}}{% endblock title %}
{% block head %}
	{{ form.media.css }}
{% endblock head %}


{% block content %}
<div class="container">
	<div class="row mt-5 select2-form">
		<form method="POST">
		{% csrf_token %}
		{{form.as_p}} 
		{% if not object %}
		<p>"test song"という曲が登録されているので、そちらをお使いください。</p>
		<p>また、新しく曲を登録することも可能です。</p>
		{% endif %}
		<input type="submit" value="{% if object %}{% trans 'Update' %}{% else %}{% trans 'Post' %}{% endif %}">
		</form>
		<a href="#" id="add_song_link">{% trans 'Add song' %}</a>
	</div>

	
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{{ form.media.js }}
{% load static %}
<script src="{% static 'js/add_song.js' %}" song_create_popup_url="{% url 'musics:song_create_popup' %}"></script>
{% endblock content %}

mlog_project/templates/entry/entry_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title%} {% if song %}{{song.song_name}}{% elif artist %}{{artist.artist_name}}{% endif %}の記事一覧 | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row mt-5">
		<h2>{% if song %}{{song.song_name}}{% elif artist %}{{artist.artist_name}}{% endif %}の記事一覧</h2>
		{% if entry_list %}
			<div class="row">
				{% include 'common_templates/entry_card_with_writer.html' %}
			</div>
		{% else %}
			<p>{% trans 'There is no entry.' %}</p>
		{% endif %}
	</div>
	
	{% include 'common_templates/pagination.html' %}
</div>
{% endblock content %}