mlog_project/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import (SignUpView, 
					LoginView, 
					UserDetailView, 
					UserUpdateView, 
					UserEntryListView,
					UserPasswordChangeView,
					UserPasswordChangeDoneView,
					UserPasswordResetView,
					UserPasswordResetDoneView,
					UserPasswordResetConfirmView,
					UserPasswordResetCompleteView,
					UserActiveStatusUpdateView,
)

app_name = 'accounts'
urlpatterns = [
	path('signup/',SignUpView.as_view(), name='signup'),
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', LogoutView.as_view(template_name='accounts/loggedout.html'), name='logout'),

	path('password/', UserPasswordChangeView.as_view(), name='password'),
	path('password/changed/', UserPasswordChangeDoneView.as_view(), name='passwordchanged'),
	path('password/reset/', UserPasswordResetView.as_view(), name='passwordreset'),
	path('password/reset/done/', UserPasswordResetDoneView.as_view(), name='passwordresetdone'),
	path('password/reset/confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='passwordresetconfirm'),
	path('password/reset/complete/', UserPasswordResetCompleteView.as_view(), name='passwordresetcomplete'),
	
	path('detail/<str:username>/', UserDetailView.as_view(), name='detail'),
	path('detail/<str:username>/entry/', UserEntryListView.as_view(), name='userentrylist'),
	path('update/', UserUpdateView.as_view(), name='update'),
	path('update/active_status/', UserActiveStatusUpdateView.as_view(), name='active_status'),
]

mlog_project/comments/urls.py
from django.urls import path

from .views import (
	CommentCreateView,
	CommentListView,
	CommentUpdateView,
	CommentDeleteView,
)

app_name='comments'
urlpatterns=[
	path('create/<int:pk>/', CommentCreateView.as_view(), name='create'),
	path('list/<int:pk>/', CommentListView.as_view(), name='list'),
	path('update/<int:pk>/', CommentUpdateView.as_view(), name='update'),
	path('delete/<int:pk>/', CommentDeleteView.as_view(), name='delete'),
]

mlog_project/entry/urls.py
from django.urls import path, include

from .views import (
	EntryDetailView,
	EntryCreateView,
	EntryUpdateView,
	EntryDeleteView,
	EntryListBySongView,
	EntryListByArtistView
)

app_name='entry'

urlpatterns=[
	path('create/', EntryCreateView.as_view(), name='create'),
	path('detail/<int:pk>/', EntryDetailView.as_view(), name='detail'),
	path('update/<int:pk>/', EntryUpdateView.as_view(), name='update'),
	path('delete/<int:pk>/', EntryDeleteView.as_view(), name='delete'),

	path('list/song/<int:pk>/', EntryListBySongView.as_view(), name='entry_list_by_song'),
	path('list/artist/<slug:slug>/', EntryListByArtistView.as_view(), name='entry_list_by_artist'),

	path('select2/', include('django_select2.urls')),
]

mlog_project/mlog/urls.py
from django.urls import path

from .views import (
					RootRedirectView,
					TopView, 
					TimelineView, 
					login_as_sample_user,
				)

app_name='mlog'
urlpatterns=[
	path('', RootRedirectView.as_view(), name='rootredirect'),
	path('top/', TopView.as_view(), name='top'),
	path('timeline/', TimelineView.as_view(), name='timeline'),
	path('login_as_sample_user/', login_as_sample_user, name='login_as_sample_user'),
]

mlog_project/mlog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import debug_toolbar


urlpatterns = [
    path('mlog_admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='accounts'),
    #path('accounts/', include('allauth.urls')),
    path('', include('mlog.urls'), name='mlog'),
    path('search/', include('search.urls'), name='search'),
    path('comments/', include('comments.urls'), name='comments'),
    path('likes/', include('likes.urls'), name='likes'),
    path('favorites/', include('favorite_artists.urls'), name='favorites'),
    path('follow/', include('follow.urls'), name='follow'),
    path('musics/', include('musics.urls'), name='musics'),
    path('entry/', include('entry.urls'), name='entry'),
    path('notifications/', include('notifications.urls'), name='notifications'),
    path('contacts/', include('contacts.urls'), name='contacts'),
    path('select2/', include('django_select2.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('__debug__/', include(debug_toolbar.urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mlog_project/comments/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from accounts.models import User
from entry.models import Entry

class Comment(models.Model):
	comment = models.TextField(verbose_name=_('comment'), max_length=200)
	entry = models.ForeignKey(Entry, on_delete=models.CASCADE, verbose_name=_('entry'))
	author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('author'))

	def __str__(self):
		return '%s comment to %s'%(self.author.username, self.entry.title)

mlog_project/comments/forms.py
from django.forms import ModelForm

from .models import Comment


class CommentForm(ModelForm):
	class Meta:
		model = Comment
		fields = ('comment',)

mlog_project/comments/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.exceptions import ObjectDoesNotExist

from entry.models import Entry
from accounts.models import User

from .models import Comment
from .forms import CommentForm


class CommentCreateView(LoginRequiredMixin, CreateView):
	form_class = CommentForm
	template_name = 'comments/comment_form.html'

	def form_valid(self, form):
		form.instance.author = User.objects.get(username=self.request.user.username)
		form.instance.entry_id = self.kwargs['pk']
		return super().form_valid(form)

	def get_success_url(self):
		return reverse('comments:list', kwargs={'pk':self.kwargs['pk']})


class CommentListView(ListView):
	model = Comment
	template_name = 'comments/list.html'

	def get_queryset(self):
		qs = super().get_queryset()
		try:
			qs = qs.select_related('entry', 'author').filter(entry_id=self.kwargs['pk'], author__is_active=True).order_by('id').reverse()
		except ObjectDoesNotExist:
			qs = qs.objects.none()
		return qs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['entry'] = Entry.objects.get(id=self.kwargs['pk'], writer__is_active=True)
		return context




def get_comment_object(pk):
	obj = get_object_or_404(Comment, pk=pk, author__is_active=True)
	entry_pk = obj.entry.id
	return (obj, entry_pk)


class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	form_class = CommentForm
	template_name = 'comments/comment_form.html'

	def test_func(self):
		obj = self.get_object()
		return obj.author == self.request.user

	def get_object(self):
		obj, self.entry_pk = get_comment_object(self.kwargs['pk'])
		return obj

	def get_success_url(self):
		return reverse('comments:list', kwargs={'pk':self.entry_pk})


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	context_object_name = 'comment'
	template_name = 'comments/delete_confirm.html'

	def test_func(self):
		comment_object = self.get_object()
		entry_object = Entry.objects.get(pk=comment_object.entry.id)
		
		return comment_object.author == self.request.user or entry_object.writer == self.request.user

	def get_object(self):
		obj, self.entry_pk = get_comment_object(self.kwargs['pk'])
		return obj

	def get_success_url(self):
		return reverse('comments:list', kwargs={'pk':self.entry_pk})

mlog_project/templates/comments/comment_form.html
{% extends 'base.html' %}
{% block title%}コメント{% if object %}更新{% else %}投稿{% endif %} | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row mt-5">
		<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="投稿">
		</form>
	</div>
</div>
{% endblock content %}

mlog_project/templates/comments/create.html
{% extends 'base.html' %}
{% block title%}コメント投稿 | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class "row mt-5">
		<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="投稿">
		</form>
	</div>
</div>
{% endblock content %}

mlog_project/templates/comments/delete_confirm.html
{% extends "base.html" %}
{% block title %}
削除しますか？ | {{block.super}}
{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form method="post">
                {% csrf_token %}
                <p>このコメントを削除しますか？</p>
				<p>記事：{{comment.entry.title}}</p>
				<p>コメント：{{comment.comment}}</p>
                <input type="submit" value="削除">
                <a href="{% url 'comments:list' comment.entry.id %}"><input type="button" value="キャンセル"></a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

mlog_project/templates/comments/list.html
{% extends 'base.html' %}
{% block title%} コメントリスト | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row mt-5">
        <h1><a href="{% url 'entry:detail' entry.id %}">{{entry.title}}</a>へのコメント</h1>
	    {% if comment_list%}
            {% for comment in comment_list %}
            <div class="col-lg-8 comment">
                <div class="card comment-card">
                    <div class="card-body">
                        <p>{{comment.comment}} by <a href="{% url 'accounts:detail' comment.author.username %}">{{comment.author}}</a></p>
                        {% if comment.author.username == user.username %}<a href="{% url 'comments:update' comment.id %}"> 更新</a>{% endif %}
                        {% if comment.author.username == user.username or comment.entry.writer == user %}<a href="{% url 'comments:delete' comment.id %}"> 削除</a>{% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
        コメントはありません。
        {% endif %}

         <p><a href="{% url 'comments:create' entry.id %}">コメントする</a></p>

	</div>
</div>
{% endblock content %}