mlog_project/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import (SignUpView, 
					LoginView, 
					UserDetailView, 
					UserUpdateView, 
					UserEntryListView,
					UserPasswordChangeView,
					UserPasswordChangeDoneView,
					UserPasswordResetView,
					UserPasswordResetDoneView,
					UserPasswordResetConfirmView,
					UserPasswordResetCompleteView,
					UserActiveStatusUpdateView,
)

app_name = 'accounts'
urlpatterns = [
	path('signup/',SignUpView.as_view(), name='signup'),
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', LogoutView.as_view(template_name='accounts/loggedout.html'), name='logout'),

	path('password/', UserPasswordChangeView.as_view(), name='password'),
	path('password/changed/', UserPasswordChangeDoneView.as_view(), name='passwordchanged'),
	path('password/reset/', UserPasswordResetView.as_view(), name='passwordreset'),
	path('password/reset/done/', UserPasswordResetDoneView.as_view(), name='passwordresetdone'),
	path('password/reset/confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='passwordresetconfirm'),
	path('password/reset/complete/', UserPasswordResetCompleteView.as_view(), name='passwordresetcomplete'),
	
	path('detail/<str:username>/', UserDetailView.as_view(), name='detail'),
	path('detail/<str:username>/entry/', UserEntryListView.as_view(), name='userentrylist'),
	path('update/', UserUpdateView.as_view(), name='update'),
	path('update/active_status/', UserActiveStatusUpdateView.as_view(), name='active_status'),
]

mlog_project/mlog/urls.py
from django.urls import path

from .views import (
					RootRedirectView,
					TopView, 
					TimelineView, 
					login_as_sample_user,
				)

app_name='mlog'
urlpatterns=[
	path('', RootRedirectView.as_view(), name='rootredirect'),
	path('top/', TopView.as_view(), name='top'),
	path('timeline/', TimelineView.as_view(), name='timeline'),
	path('login_as_sample_user/', login_as_sample_user, name='login_as_sample_user'),
]

mlog_project/mlog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import debug_toolbar


urlpatterns = [
    path('mlog_admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='accounts'),
    #path('accounts/', include('allauth.urls')),
    path('', include('mlog.urls'), name='mlog'),
    path('search/', include('search.urls'), name='search'),
    path('comments/', include('comments.urls'), name='comments'),
    path('likes/', include('likes.urls'), name='likes'),
    path('favorites/', include('favorite_artists.urls'), name='favorites'),
    path('follow/', include('follow.urls'), name='follow'),
    path('musics/', include('musics.urls'), name='musics'),
    path('entry/', include('entry.urls'), name='entry'),
    path('notifications/', include('notifications.urls'), name='notifications'),
    path('contacts/', include('contacts.urls'), name='contacts'),
    path('select2/', include('django_select2.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('__debug__/', include(debug_toolbar.urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mlog_project/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

	def get_image_path(self,filename):
		from uuid import uuid4
		import os

		prefix = 'images/users/accounts/profile/'
		name = str(uuid4()).replace('-', '')
		ext = os.path.splitext(filename)[-1]
		
		return prefix + name + ext

	handle = models.CharField(verbose_name=_('handle name'), max_length=20)
	biograph = models.TextField(verbose_name=_('biograph'), max_length=200, blank=True)
	profile_image = models.ImageField(
		verbose_name = _('profile image'),
		upload_to=get_image_path,
		default='images/defaults/accounts/profile/default.jpg'
		)

mlog_project/entry/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from musics.models import Song
from accounts.models import User


class Entry(models.Model):
	title = models.CharField(verbose_name=_('title'), max_length=30)
	content = models.TextField(_('content'))
	writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='entrys_writer' ,verbose_name=_('writer'))
	created_at = models.DateTimeField(verbose_name=_('created at'))
	updated_at = models.DateTimeField(verbose_name=_('updated at'))
	song = models.ForeignKey(Song, on_delete=models.PROTECT, related_name='featured_song', verbose_name=_('song'))

	def save(self, *args, **kwargs):
		if not self.id:
			self.created_at = timezone.now()
		self.updated_at = timezone.now()
		return super(Entry, self).save(*args, **kwargs)

	def __str__(self):
	    return '%s written by %s (Song:%s)'%(self.title, self.writer,self.song)

mlog_project/accounts/forms.py
from django.forms.models import ModelForm
from .models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm

class SignUpForm(UserCreationForm):
	class Meta:
		model = User
		fields = ('username', 'password1', 'password2', 'handle', 'biograph', 'profile_image')


class UserUpdateForm(UserChangeForm):
	password = None

	class Meta:
		model = User
		fields = ('handle', 'biograph', 'profile_image')


class UserPasswordChangeForm(PasswordChangeForm):
	class Meta:
		model = User


class UserActiveStatusUpdateForm(ModelForm):
	class Meta:
		model = User
		fields = ('is_active',)
		labels = {
			'is_active':'アクティブ状態'
		}

		help_texts = {
			'is_active':'',
		}

mlog_project/accounts/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import CreateView, DetailView, UpdateView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.views import LoginView as auth_login_view, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.contrib.auth import login

from entry.models import Entry
from likes.models import Like
from follow.models import Follow

from .forms import SignUpForm, UserUpdateForm, UserPasswordChangeForm, UserActiveStatusUpdateForm
from .models import User
from activity.tasks import user_checked_activity


class SignUpView(CreateView):
	form_class = SignUpForm
	template_name = 'accounts/signup.html'

	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			return redirect('accounts:detail', username=self.request.user.username)
		return super().get(request, *args, **kwargs)

	def form_valid(self, form):
		to_return = super().form_valid(form)
		login(self.request, self.object, backend='django.contrib.auth.backends.ModelBackend')
		return to_return

	def get_success_url(self):
		return reverse('accounts:detail', kwargs={'username':self.object.username})

class LoginView(auth_login_view):
	template_name = 'accounts/login.html'
	redirect_authenticated_user = True

	def get_success_url(self):
		if self.request.GET.get('next'):
			return self.request.GET.get('next')
		return reverse('accounts:detail', kwargs={'username':self.request.user.username})


class UserDetailView(DetailView):
	context_object_name = 'detail_user'

	def get(self, request, *args, **kwargs):
		user_checked_activity.delay(self.kwargs['username'], request.user.username)
		return super().get(request, *args, **kwargs)

	def get_object(self):
		return get_object_or_404(User, username=self.kwargs['username'], is_active=True)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['entries'] = Entry.objects.select_related('writer', 'song').prefetch_related('song__artist').filter(writer__username=self.kwargs['username']).order_by('id').reverse()[:5]
		context['follow_count'] = Follow.objects.filter(user__username=self.kwargs['username'], follower__is_active=True).count()
		context['follower_count'] = Follow.objects.filter(follower__username=self.kwargs['username'], user__is_active=True).count()
		context['liked_entry_count'] = Like.objects.filter(user__username=self.kwargs['username'], entry__writer__is_active=True).count()

		if self.request.user.is_authenticated:
			user = get_object_or_404(User, username=self.request.user.username)	
			follow_user = get_object_or_404(User, username=self.kwargs['username'])
			context['is_myself'] = (user==follow_user)
			context['is_following'] = Follow.objects.filter(user__username=user.username, follower__username=follow_user.username).exists()
		
		return context


class UserUpdateView(LoginRequiredMixin,UpdateView):
	form_class = UserUpdateForm
	
	def get_object(self):
		return get_object_or_404(User, username=self.request.user.username)

	def get_success_url(self):
		return reverse('accounts:detail', kwargs={'username':self.request.user.username})


class UserEntryListView(ListView):
	model = Entry
	template_name = 'accounts/user_entry_list.html'
	paginate_by = 20

	def get_queryset(self):
		qs = super().get_queryset()
		return qs.select_related('writer', 'song').prefetch_related('song__artist').filter(writer__username=self.kwargs['username'], writer__is_active=True).order_by('id').reverse()

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['detail_user'] = get_object_or_404(User, username=self.kwargs.get('username'), is_active=True)
		return context


class UserPasswordChangeView(PasswordChangeView):
	template_name = 'accounts/passwordchange.html'
	form_class = UserPasswordChangeForm
	success_url = reverse_lazy('accounts:passwordchanged')


class UserPasswordChangeDoneView(PasswordChangeDoneView):
	template_name = 'accounts/passwordchangedone.html'


class UserPasswordResetView(PasswordResetView):
	template_name = 'accounts/password_reset.html'
	form_class = PasswordResetForm
	success_url = reverse_lazy('accounts:passwordresetdone')
	email_template_name = 'accounts/password_reset_email.html'


class UserPasswordResetDoneView(PasswordResetDoneView):
	template_name = 'accounts/password_reset_done.html'
	

class UserPasswordResetConfirmView(PasswordResetConfirmView):
	template_name = 'accounts/password_reset_confirm.html'
	success_url = reverse_lazy('accounts:passwordresetcomplete')


class UserPasswordResetCompleteView(PasswordResetCompleteView):
	template_name = 'accounts/password_reset_complete.html'


class UserActiveStatusUpdateView(LoginRequiredMixin, UpdateView):
	form_class = UserActiveStatusUpdateForm
	template_name = 'accounts/active_status.html'

	def get_object(self):
		obj = User.objects.get(username=self.request.user.username)
		return obj
	
	def get_success_url(self):
		return reverse('mlog:top')

mlog_project/templates/accounts/active_status.html
{% extends 'base.html' %}
{% block title %}{% trans 'Do you delete your account?' %} | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col mt-5">
			{% trans 'Uncheck if you delete your account.' %}
			<form method="POST">
				{% csrf_token %}
				{{form.as_p}}
				<input type="submit" value="{% trans 'Delete' %}">
			</form>
			<a href="{% url 'accounts:update' %}"><input type="button" value="{% trans 'Cancel' %}"></a>
		</div>
	</div>
</div>
{% endblock content %}

mlog_project/templates/accounts/followerlist.html
{% extends 'base.html' %}
{% block title%} {{this_page_handle}} ({{this_page_username}})のフォロワー一覧 | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col mt-5">
			<h1><a href="{% url 'accounts:detail' this_page_username %}">{{this_page_handle}}</a>のフォロワー一覧</h1>

			{% if followers %}
			{% for follower in followers%}
			<p><a href='{% url 'accounts:detail' follower.user.username%}'><img src="/media/{{follower.user.profile_image}}" height="{{profile_image_size.HEIGHT}}" width="{{profile_image_size.WIDTH}}"/>{{follower.user.handle}}({{follower.user.username}})</a></p>
			{% endfor %}
			{% else %}
			フォロワーはいません
			{% endif %}
		</div>
	</div>
</div>
{% endblock content %}

mlog_project/templates/accounts/followlist.html
{% extends 'base.html' %}
{% block title%} {{this_page_handle}} ({{this_page_username}})のフォロー一覧 | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col mt-5">
			<h1><a href="{% url 'accounts:detail' this_page_username %}">{{this_page_handle}}</a>のフォロー一覧</h1>

			{% if follows %}
			{% for follow in follows%}
			<p><a href='{% url 'accounts:detail' follow.follower %}'><img src="/media/{{follow.follower.profile_image}}" height="{{profile_image_size.HEIGHT}}" width="{{profile_image_size.WIDTH}}"/>{{follow.follower.handle}}({{follow.follower}})</a></p>
			{% endfor %}
			{% else %}
			フォローしている人はいません
			{% endif %}
		</div>
	</div>
</div>
{% endblock content %}

mlog_project/templates/accounts/login.html
{% extends 'base.html' %}
{% load i18n %}
{% block title%}{% trans 'Login' %} | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col mt-5">
			<form method="POST">
				{% csrf_token %}
				{{form.as_p}}
				<input type="submit" value="{% trans 'Login' %}">

				<p><a href="{% url 'accounts:passwordreset' %}">{% trans 'Reset Password' %}</a></p>
			</form>
			<a href="{% url 'mlog:login_as_sample_user' %}"><input type="button" value="{% trans 'Login as sample user' %}"></a>
		</div>
	</div>
</div>
{% endblock content %}

mlog_project/templates/accounts/password_reset.html
{% extends 'base.html' %}
{% block title%}パスワードリセット | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col mt-5">
			<form method="POST">
				{% csrf_token %}
				{{form.as_p}}
				<input type="submit" value="リセット">
			</form>
		</div>
	</div>
</div>
{% endblock content %}

mlog_project/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% block title%}パスワードリセット完了 | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col mt-5">
			<p>パスワードリセットが完了しました。</p>
			<a href="{% url 'accounts:login' %}">ログイン</a>
		</div>
	</div>
</div>
{% endblock content %}

mlog_project/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% block title%}パスワードリセット確認 | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col mt-5">
			<form method="POST">
				{% csrf_token %}
				{{form.as_p}}
				<input type="submit" value="リセット">
			</form>
		</div>
	</div>
</div>
{% endblock content %}

mlog_project/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% block title%}パスワードリセット | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col mt-5">
			<p>パスワードリセット用メールが送信されました。</p>
		</div>
	</div>
</div>
{% endblock content %}

mlog_project/templates/accounts/password_reset_email.html
{{ email }}で登録されたアカウントのパスワードリセットが要求されました。
以下のリンクでパスワードをリセットできます。
{{ protocol}}://{{ domain }}{% url 'accounts:passwordresetconfirm' uidb64=uid token=token %}

mlog_project/templates/accounts/passwordchange.html
{% extends 'base.html' %}
{% block title%}パスワード変更 | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col mt-5">
			<form method="POST">
				{% csrf_token %}
				{{form.as_p}}
				<input type="submit" value="変更">
			</form>
		</div>
	</div>
</div>
{% endblock content %}

mlog_project/templates/accounts/signup.html
{% extends 'base.html' %}
{% load i18n %}
{% block title%}{% trans 'Sign Up' %} | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col mt-5">
			<form method="post" action="{% url 'accounts:signup' %}" enctype="multipart/form-data">
				{% csrf_token %}
				<table>
					<tr>
						<td>{{form.username.label_tag}}</td>
						<td>{{form.username}}</td>
					</tr>
					<tr>
						<td>{{form.handle.label_tag}}</td>
						<td>{{form.handle}}</td>
					</tr>
					<tr>
						<td>{{form.password1.label_tag}}</td>
						<td>{{form.password1}}</td>
					</tr>
					<tr>
						<td>{{form.password2.label_tag}}</td>
						<td>{{form.password2}}</td>
					</tr>
					<tr>
						<td>{{form.biograph.label_tag}}</td>
						<td>{{form.biograph}}</td>
					</tr>
					<tr>
						<td>{{form.profile_image.label_tag}}</td>
						<td>{{form.profile_image}}</td>
					</tr>
				</table>
				<input type="submit" value="{% trans 'Sign Up' %}"/>
				{% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                        <p>{{ error }}</p>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
			</form>
		</div>
	</div>
</div>
{% endblock content %}

mlog_project/templates/accounts/user_entry_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title%} {{detail_user.handle}} ({{detail_user.username}})の投稿一覧 | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col mt-5">
			<h2><a href="{% url 'accounts:detail' detail_user.username %}">{{detail_user.handle}}</a>の投稿</h2>
			<div class="row">
				{% if entry_list %}
					{% include 'common_templates/entry_card_without_writer.html' %}
				{% else %}
					<p>{% trans 'There is no entry.' %}</p>
			{% endif %}
			</div>
		</div>
	</div>
	{% include 'common_templates/pagination.html' %}
</div>
{% endblock content %}

mlog_project/templates/accounts/user_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block title%}{% trans 'Update profile' %} | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col mt-5">
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}
				<input type="submit" value="{% trans 'Update' %}">
			</form>
		</div>
	</div>
	<div class="row mt-5">
		<a href="{% url 'accounts:password' %}"><input type="button" value="{% trans 'Change Password' %}"></a>
	</div>
	<div class="row mt-5">
		<a href="{% url 'accounts:active_status' %}">{% trans 'Delete account' %}</a>
	</div>
</div>
{% endblock content %}

mlog_project/templates/accounts/usersearch.html
{% extends 'base.html' %}
{% block title%} 「{{keyword}}」の検索結果 | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class "row mt-5">
    「{{keyword}}」の検索結果
	{% if user_list %}
		{% for auser in user_list%}
        <p><a href="{% url 'accounts:detail' auser.username %}">{{auser.handle}} ({{auser.username}})</a></p>
        {% endfor %}
	{% else %}
	<p>検索結果はありません。</p>
	{% endif %}

	</div>
</div>
{% endblock content %}