mlog_project/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import (SignUpView, 
					LoginView, 
					UserDetailView, 
					UserUpdateView, 
					UserEntryListView,
					UserPasswordChangeView,
					UserPasswordChangeDoneView,
					UserPasswordResetView,
					UserPasswordResetDoneView,
					UserPasswordResetConfirmView,
					UserPasswordResetCompleteView,
					UserActiveStatusUpdateView,
)

app_name = 'accounts'
urlpatterns = [
	path('signup/',SignUpView.as_view(), name='signup'),
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', LogoutView.as_view(template_name='accounts/loggedout.html'), name='logout'),

	path('password/', UserPasswordChangeView.as_view(), name='password'),
	path('password/changed/', UserPasswordChangeDoneView.as_view(), name='passwordchanged'),
	path('password/reset/', UserPasswordResetView.as_view(), name='passwordreset'),
	path('password/reset/done/', UserPasswordResetDoneView.as_view(), name='passwordresetdone'),
	path('password/reset/confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='passwordresetconfirm'),
	path('password/reset/complete/', UserPasswordResetCompleteView.as_view(), name='passwordresetcomplete'),
	
	path('detail/<str:username>/', UserDetailView.as_view(), name='detail'),
	path('detail/<str:username>/entry/', UserEntryListView.as_view(), name='userentrylist'),
	path('update/', UserUpdateView.as_view(), name='update'),
	path('update/active_status/', UserActiveStatusUpdateView.as_view(), name='active_status'),
]

mlog_project/entry/urls.py
from django.urls import path, include

from .views import (
	EntryDetailView,
	EntryCreateView,
	EntryUpdateView,
	EntryDeleteView,
	EntryListBySongView,
	EntryListByArtistView
)

app_name='entry'

urlpatterns=[
	path('create/', EntryCreateView.as_view(), name='create'),
	path('detail/<int:pk>/', EntryDetailView.as_view(), name='detail'),
	path('update/<int:pk>/', EntryUpdateView.as_view(), name='update'),
	path('delete/<int:pk>/', EntryDeleteView.as_view(), name='delete'),

	path('list/song/<int:pk>/', EntryListBySongView.as_view(), name='entry_list_by_song'),
	path('list/artist/<slug:slug>/', EntryListByArtistView.as_view(), name='entry_list_by_artist'),

	path('select2/', include('django_select2.urls')),
]

mlog_project/mlog/urls.py
from django.urls import path

from .views import (
					RootRedirectView,
					TopView, 
					TimelineView, 
					login_as_sample_user,
				)

app_name='mlog'
urlpatterns=[
	path('', RootRedirectView.as_view(), name='rootredirect'),
	path('top/', TopView.as_view(), name='top'),
	path('timeline/', TimelineView.as_view(), name='timeline'),
	path('login_as_sample_user/', login_as_sample_user, name='login_as_sample_user'),
]

mlog_project/mlog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import debug_toolbar


urlpatterns = [
    path('mlog_admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='accounts'),
    #path('accounts/', include('allauth.urls')),
    path('', include('mlog.urls'), name='mlog'),
    path('search/', include('search.urls'), name='search'),
    path('comments/', include('comments.urls'), name='comments'),
    path('likes/', include('likes.urls'), name='likes'),
    path('favorites/', include('favorite_artists.urls'), name='favorites'),
    path('follow/', include('follow.urls'), name='follow'),
    path('musics/', include('musics.urls'), name='musics'),
    path('entry/', include('entry.urls'), name='entry'),
    path('notifications/', include('notifications.urls'), name='notifications'),
    path('contacts/', include('contacts.urls'), name='contacts'),
    path('select2/', include('django_select2.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('__debug__/', include(debug_toolbar.urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mlog_project/musics/urls.py
from django.urls import path, include

from .views import (
	ArtistDetailView,
	SongDetailView,
	ArtistCreateView,
	SongCreateView,
	PopupArtistCreateView,
	PopupSongCreateView,
	PopupGenreCreateView,
	GenreCreateView,
	GenreListView,
	ArtistByGenreListView,
	ArtistUpdateView,
	SongUpdateView,
	SongByArtistListView,
	search_spotify_tracks,
	select_spotify_tracks,
)


app_name='musics'

urlpatterns=[
	path('detail/artist/<slug:slug>/', ArtistDetailView.as_view(), name='artist_detail'),
	path('detail/song/<int:pk>/', SongDetailView.as_view(), name='song_detail'),

	path('create/song/', SongCreateView.as_view(), name='song_create'),
	path('create/artist/', ArtistCreateView.as_view(), name='artist_create'),
	path('create/genre/', GenreCreateView.as_view(), name='genre_create'),

	path('create/song/popup/', PopupSongCreateView.as_view(), name='song_create_popup'),
	path('create/artist/popup/', PopupArtistCreateView.as_view(), name='artist_create_popup'),
	path('create/genre/popup/', PopupGenreCreateView.as_view(), name='genre_create_popup'),

	path('update/artist/<str:slug>/', ArtistUpdateView.as_view(), name='artist_update'),
	path('update/song/<int:pk>/', SongUpdateView.as_view(), name='song_update'),

	path('list/genre/', GenreListView.as_view(), name='genre_list'),
	path('list/genre/<str:genre_name>/artist/', ArtistByGenreListView.as_view(), name='artist_by_genre'),
	path('list/artist/<str:slug>/song/', SongByArtistListView.as_view(), name='song_by_artist'),

	path('search_spotify_tracks/', search_spotify_tracks, name='search_spotify_tracks'),
	path('select_spotify_tracks/', select_spotify_tracks, name='select_spotify_tracks'),

	path('select2/', include('django_select2.urls')),
]

mlog_project/musics/models.py
from django.db import models

from concurrency.fields import AutoIncVersionField


class Genre(models.Model):
    genre_name = models.CharField(max_length=20)

    def __str__(self):
        return self.genre_name


class Artist(models.Model):
    artist_name = models.CharField(max_length=30)
    genre = models.ManyToManyField(Genre)
    artist_biograph = models.TextField(max_length=200, blank=True)
    belong_to = models.ForeignKey("self", on_delete=models.PROTECT, blank=True, null=True)
    slug = models.SlugField(verbose_name='Unique Artist ID')
    version = AutoIncVersionField()
    
    def __str__(self):
        return self.artist_name


class Song(models.Model):
    song_name = models.CharField(max_length=30)
    artist = models.ManyToManyField(Artist)
    genre = models.ManyToManyField(Genre)
    original = models.ForeignKey('self', on_delete=models.PROTECT, blank=True, null=True)
    spotify_link = models.URLField(blank=True)
    spotify_preview_url = models.URLField(blank=True)
    artwork_url = models.URLField(blank=True)
    version = AutoIncVersionField()

    def __str__(self):
        names=', '.join(str(artist) for artist in self.artist.all())
        return '%s by %s'%(self.song_name, str(names))

mlog_project/musics/forms.py
from django.forms import ModelForm

from django_select2 import forms as s2forms
from concurrency.forms import ConcurrentForm

from .models import Artist, Song, Genre


class ArtistWidget(s2forms.ModelSelect2MultipleWidget):
	search_fields = [
		'artist_name__icontains',
		'slug__icontains',
	]


class ArtistBelongToWidget(s2forms.ModelSelect2Widget):
	search_fields = [
		'artist_name__icontains',
		'slug__icontains'
	]


class GenreWidget(s2forms.ModelSelect2MultipleWidget):
	search_fields = [
		'genre_name__icontains'
	]


class ArtsitForm(ConcurrentForm):
	class Meta:
		model = Artist
		fields = ('artist_name', 'genre', 'slug', 'artist_biograph', 'belong_to', 'version')
		widgets = {
			'genre':GenreWidget,
			'belong_to':ArtistBelongToWidget,
		}


class SongForm(ConcurrentForm):
	class Meta:
		model = Song
		fields = ('song_name', 'artist', 'genre', 'spotify_link', 'spotify_preview_url', 'artwork_url', 'version')
		widgets = {
			'artist':ArtistWidget,
			'genre':GenreWidget,
		}


class GenreForm(ModelForm):
	class Meta:
		model = Genre
		fields = ('genre_name',)

mlog_project/musics/views.py
from django.http.response import JsonResponse
from django.shortcuts import render
from django.views.generic import DetailView, CreateView, ListView, UpdateView
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse_lazy

from entry.models import Entry
from favorite_artists.models import FavoriteArtist

from activity.tasks import artist_checked_activity, song_checked_activity, genre_checked_activity

from .models import Artist, Song, Genre
from .forms import ArtsitForm, SongForm, GenreForm
from .spotify_utils import GetSpotifyData


class GenreCreateView(CreateView):
	form_class = GenreForm
	template_name = 'musics/genre_form.html'

	def get_success_url(self):
		return reverse_lazy('entry:create')


class PopupGenreCreateView(GenreCreateView):

	def form_valid(self, form):
		genre = form.save()
		context = {
			'object_name':str(genre),
			'object_pk':genre.pk,
			'function_name':'add_genre'
		}
		return render(self.request, 'musics/close.html', context)


class ArtistCreateView(CreateView):
	form_class = ArtsitForm
	template_name = 'musics/artist_form.html'

	def get_success_url(self):
		return reverse_lazy('musics:artist_detail', kwargs={'slug':self.object.slug})


class PopupArtistCreateView(ArtistCreateView):

	def form_valid(self, form):
		artist=form.save()
		context={
			'object_name':str(artist),
			'object_pk':artist.pk,
			'function_name':'add_artist'
		}
		return render(self.request, 'musics/close.html', context)


class SongCreateView(CreateView):
	form_class = SongForm
	template_name = 'musics/song_form.html'

	def get_success_url(self):
		return reverse_lazy('musics:song_detail', kwargs={'pk':self.object.id})


class PopupSongCreateView(SongCreateView):

	def form_valid(self, form):
		song = form.save()
		context = {
			'object_name':str(song),
			'object_pk':song.pk,
			'function_name':'add_song'
		}
		return render(self.request, 'musics/close.html', context)


class SongDetailView(DetailView):
	model = Song
	template_name = 'musics/song_detail.html'

	def get(self, request, *args, **kwargs):
		song_checked_activity.delay(self.kwargs['pk'], request.user.username)
		return super().get(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['entries'] = Entry.objects.filter(
			song=self.kwargs['pk']
			).select_related(
				'song',
				'writer'
			).prefetch_related(
				'song__artist',
			).order_by(
				'created_at',
			).reverse()[:3]
		return context


class ArtistDetailView(DetailView):
	model = Artist
	template_name = 'musics/artist_detail.html'

	def get(self, request, *args, **kwargs):
		artist_checked_activity.delay(self.kwargs.get('slug'), request.user.username)
		return super().get(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		context['entries'] = Entry.objects.filter(
			song__artist__slug=self.kwargs['slug']
			).select_related(
				'writer',
				'song'
			).prefetch_related(
				'song__artist'
			).order_by(
				'created_at',
			).reverse()


		context['members'] = Artist.objects.filter(belong_to__slug=self.kwargs['slug']).order_by('slug')

		context['song_list'] = Song.objects.filter(
			artist__slug=self.kwargs['slug']
			).order_by(
				'song_name'
				).prefetch_related(
					'artist'
				)[:4]

		if self.request.user.is_authenticated:
			try:
				context['fav_status'] = FavoriteArtist.objects.get(user__username=self.request.user.username, artist__slug=self.kwargs['slug'])
			except ObjectDoesNotExist:
				context['fav_status'] = FavoriteArtist.objects.none()

		return context


class ArtistUpdateView(UpdateView):
	model = Artist
	form_class = ArtsitForm
	template_name = 'musics/artist_form.html'

	def get_success_url(self):
		return reverse_lazy('musics:artist_detail', kwargs={'slug':self.object.slug})


class SongUpdateView(UpdateView):
	model = Song
	form_class = SongForm
	template_name = 'musics/song_form.html'

	def get_success_url(self):
		return reverse_lazy('musics:song_detail', kwargs={'pk':self.object.id})


class GenreListView(ListView):
	model = Genre
	ordering = ['genre_name']
	template_name = 'mlog/genre_list.html'


class ArtistByGenreListView(ListView):
	model = Artist
	template_name = 'musics/artist_by_genre_list.html'

	def get(self, request, *args, **kwargs):
		genre_checked_activity.delay(self.kwargs['genre_name'], request.user.username)
		return super().get(request, *args, **kwargs)

	def get_queryset(self):
		qs = super().get_queryset()
		return qs.filter(genre__genre_name=self.kwargs['genre_name']).order_by('slug')

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['genre'] = Genre.objects.get(genre_name=self.kwargs['genre_name'])
		return context


class SongByArtistListView(ListView):
	model = Song
	template_name = 'musics/song_by_artist_list.html'
	paginate_by = 20

	def get_queryset(self):
		qs = super().get_queryset()
		return qs.filter(artist__slug=self.kwargs['slug']).order_by('song_name')

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['artist'] = Artist.objects.get(slug=self.kwargs['slug'])
		return context


def search_spotify_tracks(request):
	if request.method=='POST':
		search_keywords = request.POST.get('search_keywords')
		sp = GetSpotifyData()
		results = sp.search_track(search_keywords)
		d = {
			'results':results,
		}
		return JsonResponse(d)


def select_spotify_tracks(request):
	import json
	
	if request.method=='GET':
		return render(request, 'musics/spotify_track_select.html')

	if request.method=='POST':
		selected_track = json.loads(request.POST.get('selected_track'))
		spotify_link = selected_track['spotify_link']
		preview_url = selected_track['preview_url']
		artwork_url = selected_track['artwork_url']
		context = {
			'spotify_link':spotify_link,
			'preview_url':preview_url,
			'artwork_url':artwork_url,
		}
		return render(request, 'musics/close_select_spotify_tracks.html', context)

mlog_project/templates/musics/artist_by_genre_list.html
{% extends 'base.html' %}
{% block title%} {{genre.genre_name}}に登録されいるアーティスト一覧 | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row mt-5">
	{% if artist_list %}
	{% include 'common_templates/artist_card_for_list.html' %}
	{% else %}
	<p>{{genre.genre_name}}に登録されいるアーティストはいません。</p>
	{% endif %}
	</div>
</div>
{% endblock content %}

mlog_project/templates/musics/artistcreate.html
{% extends 'base.html' %}
{% block title%}アーティスト登録 | {{block.super}}{% endblock title %}
{% block head %}
	{{ form.media.css }}
	<style>
		input,select{width:50%}
	</style>
{% endblock head %}
{% block content %}
<div class="container">
	<div class "row mt-5">
		<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="登録">
		</form>
		<a href="javascript:void(0)" onclick="window.open('{% url 'musics:genre_create_popup' %}','subwin_genre')">ジャンルを追加</a>
	</div>
</div>
</form>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{{ form.media.js }}
<script>
	function add_genre(name,pk){
		var select=document.getElementById('id_genre');
		var option=document.createElement('option');
		option.setAttribute('value',pk);
		option.innerHTML=name;

		select.add(option,0);
		select.options[0].selected=true;
	}
</script>
{% endblock content %}

mlog_project/templates/musics/artistdetail.html
{% extends 'base.html' %}
{% block title%}{{artist.artist_name}} | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class "row mt-5">
        <h1>{{artist.artist_name}}</h1>
		<h2>Biograph</h2>
		{% if artist.artist_biograph %}
		{{artist.artist_biograph}}
		{% else %}
		<p>紹介はありません。</p>
		{% endif %}

		{% if artist.belong_to %}
		<p>所属グループ</p>
		<p><a href="{% url 'musics:artist_detail' artist.belong_to.artist_name_id %}">{{ artist.belong_to.artist_name }}</a></p>
		{% endif %}

		{% if members %}
		<p>所属メンバー</p>
		{% for member in members %}
		<p><a href="{% url 'musics:artist_detail' member.artist_name_id %}">{{ member.artist_name }}</a></p>
		{% endfor %}
		{% endif %}

		<form method="POST" action="{% url 'favorite_artists:process' %}" >
			{% csrf_token %}
			<input type="hidden" value="{{artist.artist_name_id}}" name="artist_name_id">
			<input type="submit" value="{% if fav_status %}お気に入り解除{% else %}お気に入りに登録{% endif %}">
		</form>
		<p><a href="{% url 'favorite_artists:userfavorite' artist.artist_name_id %}">お気に入りに登録しているユーザ一覧</a></p>


		<h2>記事一覧</h2>
		{% if entries %}
			{% for entry in entries %}
			{% include 'common_templates/entry_card_with_writer.html' %}	
			{% endfor %}
		{% else %}
		<p>記事はありません。</p>
		{% endif %}
	</div>
</div>
{% endblock content %}

mlog_project/templates/musics/close.html
<html>
	<head>

	</head>
	<body>
		{% load static %}
		<script src="{% static 'js/close.js' %}" object_name="{{object_name}}" object_pk="{{object_pk}}" function_name="{{function_name}}"></script>
	</body>
</html>

mlog_project/templates/musics/close_select_spotfy_tracks.html
<html>
	<body>
		<script type="text/javascript">
			window.opener.add_spotify_preview_url('{{selected_track}}');
			window.close();
		</script>
	</body>
</html>

mlog_project/templates/musics/close_select_spotify_tracks.html
<html>
	<body>
		{% load static %}
		<script src="{% static 'js/close_select_spotify_tracks.js' %}" spotify_link="{{spotify_link}}" preview_url="{{preview_url}}" artwork_url="{{artwork_url}}"></script>
	</body>
</html>

mlog_project/templates/musics/close_spotify_track_select.html
<html>
	<body>
		<script type="text/javascript">
			window.opener.add_spotify_preview_url('{{selected_track}}');
			window.close();
		</script>
	</body>
</html>

mlog_project/templates/musics/genre_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block title%}{% trans 'Genre' %} {% if object%}{% trans 'Update' %}{% else %}{% trans 'Post' %}{% endif %} | {{block.super}}{% endblock title %}
{% block head %}
	{{ form.media.css }}>
{% endblock head %}
{% block content %}
<div class="container">
	<div class="row mt-5 select2-form">
		<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="{% if object%}{% trans 'Update' %}{% else %}{% trans 'Post' %}{% endif %}">
		</form>
	</div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{{ form.media.js }}
{% endblock content %}

mlog_project/templates/musics/genre_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title%} {% trans 'Genre list' %} | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row mt-5">
	{% if genre_list %}
		{% for genre in genre_list %}
		<p><a href="{% url 'musics:artist_by_genre' genre.genre_name %}">{{genre.genre_name}}</a></p>
		{% endfor %}
	{% else %}
	<p>{% trans 'There is no genre.' %}</p>
	{% endif %}
	</div>
</div>
{% endblock content %}

mlog_project/templates/musics/song_by_artist_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title%} {{artist.artist_name}}の曲一覧 | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row mt-5">
		<h2>{{artist.artist_name}}の曲一覧</h2>
		{% if song_list %}
		<div class="row">
			{% include 'common_templates/song_card_with_artist.html' %}
		</div>
		{% else %}
		<p>{% trans 'There is no song.' %}</p>
		{% endif %}
	</div>

	{% include 'common_templates/pagination.html' %}
</div>
{% endblock content %}

mlog_project/templates/musics/song_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block title%}{% trans 'Song' %} {% if object %}{% trans 'update' %}{% else %}{% trans 'post' %}{% endif %} | {{block.super}}{% endblock title %}
{% block head %}
	{{ form.media.css }}
{% endblock head %}
{% block content %}
<div class="container">
	{% if not object %}
	<p>アーティストは、"test artist"というアーティストが登録されているので、そちらをお使いください。</p>
	<p>ジャンルは、"test genre"というジャンルが登録されているので、そちらをお使いください。</p>
	<p>また、新しくアーティストやジャンルを登録することも可能です。</p>
	{% endif %}
	<div class="row mt-5 select2-form">
		<form id="song_form" method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<input type="submit" value="{% if object %}{% trans 'Update' %}{% else %}{% trans 'Post' %}{% endif %}">
		</form>
		<a href="#" id="add_artist_link">{% trans 'Add artist' %}</a>
		<a href="#" id="add_genre_link">{% trans 'Add genre' %}</a>
		<a href="#" id="add_spotify_preview_url_link">{% trans 'Select song on Spotify.' %}</a>
	</div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{{ form.media.js }}
{% load static %}
<script src="{% static 'js/add_genre.js' %}" genre_create_popup_url="{% url 'musics:genre_create_popup' %}"></script>
<script src="{% static 'js/add_artist.js' %}" add_artist_link_url="{% url 'musics:artist_create_popup' %}"></script>
<script src="{% static 'js/add_spotify_preview_url.js' %}" add_spotify_preview_url_url="{% url 'musics:select_spotify_tracks' %}"></script>
{% endblock content %}

mlog_project/templates/musics/songcreate.html
{% extends 'base.html' %}
{% block title%}曲登録 | {{block.super}}{% endblock title %}
{% block head %}
	{{ form.media.css }}
	<style>
		input,select{width:50%}
	</style>
{% endblock head %}
{% block content %}
<div class="container">
	<div class="row mt-5">
		<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="登録">
		</form>
		<a href="javascript:void(0)" onclick="window.open('{% url 'musics:artist_create_popup' %}','subwin_artist')">アーティストを追加</a>
		<a href="javascript:void(0)" onclick="window.open('{% url 'musics:genre_create_popup' %}','subwin_genre')">ジャンルを追加</a>
	</div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{{ form.media.js }}
<script>
	function add_artist(name,pk){
		var select=document.getElementById('id_artist');
		var option=document.createElement('option');
		option.setAttribute('value',pk);
		option.innerHTML=name;

		select.add(option,0);
		select.options[0].selected=true;
	}

	function add_genre(name,pk){
		var select=document.getElementById('id_genre');
		var option=document.createElement('option');
		option.setAttribute('value',pk);
		option.innerHTML=name;

		select.add(option,0);
		select.options[0].selected=true;
	}
</script>
{% endblock content %}

mlog_project/templates/musics/songdetail.html
{% extends 'base.html' %}
{% block title%}{{song.song_name}} | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class "row mt-5">
		<h1>{{song.song_name}}</h1>

		<h2>アーティスト</h2>
		<p>{% for artist in song.artist.all %}
		<a href="{% url 'musics:artist_detail' artist.artist_name_id %}">{{artist.artist_name}} </a>
		{% endfor %}</p>

		<h2>この曲の記事一覧</h2>
		{% for entry in entries %}
		<div class="card m-3 entry-list-card text-center">
			<div class="card-body">
				<div class="row">
					<div class="col">
						<a href="{% url 'entry:detail' entry.id %}"><h4 class="card-title">{{entry.title}}</h4></a>
						<a href="{% url 'accounts:detail' entry.writer.username %}"><img src="{{MEDIA_URL}}{{entry.writer.profile_image}}" class="profile-image profile-image-size-xs" /><h6 class="card-subtitle">{{entry.writer.handle}} ({{entry.writer.username}})</h6></a>
					</div>

					<div class="col">
						<p>Song:<a href="{% url 'musics:song_detail' entry.song.id %}" class="card-link">{{entry.song.song_name}}</a></p>
						<p>Artist:{% for artist in entry.song.artist.all %}<a href="{% url 'musics:artist_detail' artist.artist_name_id %}" class="card-link">{{artist.artist_name}} </a>{% endfor %}</p>
					</div>
				</div>
				
				
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock content %}

mlog_project/templates/musics/spotify_track_select.html
{% extends 'base.html' %}
{% load i18n %}
{% block title%}{% trans 'Select song on Spotify.' %} | {{block.super}}{% endblock title %}
{% block content %}
<div class="container">
	<div class="row mt-5">
		<form action="{% url 'musics:select_spotify_tracks' %}" method="POST">
			{% csrf_token %}
			<p>
				<label>Spotify track search:</label>
				<input type="search" id="search_keywords">
				<input type="button" value="{% trans 'Search' %}" id="search_btn">
				<select id="spotify_track_select"  name="selected_track">
					<option selected disabled>{% trans 'Select song' %}</option>
				</select>
			</p>
			<input type="submit" value="{% trans 'Send' %}">
		</form>
	</div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% load static %}
<script src="{% static 'js/ajax_csrf.js' %}"></script>
<script src="{% static 'js/spotify_search_ajax.js' %}" type="text/javascript" search_url="{% url 'musics:search_spotify_tracks' %}"></script>
{% endblock content %}